# Generated by Django 5.1.7 on 2025-04-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_invitation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
