# Generated by Django 5.2.5 on 2025-09-23 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACAO', 'Ação'), ('FII', 'Fundo Imobiliário (FII)'), ('CRIPTO', 'Criptomoeda'), ('TESOURO', 'Tesouro/Selic'), ('POUPANCA', 'Poupança'), ('CDB', 'CDB'), ('LCI', 'LCI'), ('LCA', 'LCA')], max_length=10, verbose_name='Tipo de Investimento')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
                ('nome_patrimonio', models.CharField(max_length=100, verbose_name='Nome do Ativo')),
                ('valor_cota', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Cota')),
                ('unidades', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Quantidade')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total')),
                ('data_compra', models.DateField(verbose_name='Data da Compra')),
                ('moeda', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar')], default='BRL', max_length=3, verbose_name='Moeda')),
                ('cotacao_dolar_pago', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cotação do Dólar')),
                ('taxa_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa Anual (%)')),
                ('aporte_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Aporte Mensal')),
                ('prazo_meses', models.IntegerField(blank=True, null=True, verbose_name='Prazo (meses)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['-data_compra'],
            },
        ),
    ]
