# Generated by Django 5.2.5 on 2025-09-23 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Rendimento')),
                ('data', models.DateField(verbose_name='Data do Rendimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimentos', to='investimentos.investimento')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
