# Generated by Django 5.2.2 on 2025-06-28 16:19

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('Nubank', 'Nubank'), ('Itaú', 'Itaú'), ('Bradesco', 'Bradesco'), ('Santander', 'Santander'), ('Banco do Brasil', 'Banco do Brasil')], max_length=50)),
                ('categoria', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Lazer', 'Lazer'), ('Compras', 'Compras'), ('Saúde', 'Saúde')], max_length=50)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10)),
                ('forma', models.CharField(choices=[('Débito', 'Débito'), ('Crédito', 'Crédito'), ('Pix', 'Pix'), ('Dinheiro', 'Dinheiro'), ('Transferência', 'Transferência')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('parcelas', models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('descricao', models.TextField(max_length=300)),
                ('data', models.DateField(default=datetime.date.today)),
                ('status_pagamento', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], default='Pendente', max_length=10)),
                ('shared_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem total compartilhada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem compartilhada')),
                ('installments', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Número de parcelas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_transactions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='financas.transaction')),
            ],
            options={
                'verbose_name': 'Compartilhamento',
                'verbose_name_plural': 'Compartilhamentos',
                'unique_together': {('transaction', 'shared_with')},
            },
        ),
        migrations.CreateModel(
            name='SharedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da parcela')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10)),
                ('installment_number', models.PositiveIntegerField(verbose_name='Número da parcela')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('transaction_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financas.transactionshare')),
            ],
            options={
                'verbose_name': 'Pagamento Compartilhado',
                'verbose_name_plural': 'Pagamentos Compartilhados',
                'ordering': ['due_date', 'installment_number'],
                'unique_together': {('transaction_share', 'installment_number')},
            },
        ),
    ]
