# Generated by Django 5.1.7 on 2025-05-01 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('Nubank', 'Nubank'), ('Itaú', 'Itaú'), ('Bradesco', 'Bradesco'), ('Santander', 'Santander'), ('Banco do Brasil', 'Banco do Brasil')], max_length=50)),
                ('categoria', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Lazer', 'Lazer'), ('Compras', 'Compras'), ('Saúde', 'Saúde')], max_length=50)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10)),
                ('forma', models.CharField(choices=[('Débito', 'Débito'), ('Crédito', 'Crédito'), ('Pix', 'Pix'), ('Dinheiro', 'Dinheiro'), ('Transferência', 'Transferência')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.TextField(max_length=300)),
                ('data', models.DateField()),
                ('status_pagamento', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], default='Pendente', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
