# Generated by Django 5.2.5 on 2025-10-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_transaction_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='categoria',
            field=models.CharField(choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Lazer', 'Lazer'), ('Compras', 'Compras'), ('Saúde', 'Saúde'), ('Casa', 'Casa'), ('Carro', 'Carro'), ('Assinatura', 'Assinatura'), ('Estudo', 'Estudo')], max_length=50),
        ),
    ]
